name: MeepcraftEvents
main: net.meepcraft.alexdgr8r.meepcraftevents.MeepcraftEvents
description: Gives Meepcraft some cool random events and stuff
author: AlexDGr8r
website: http://meepcraft.net/
version: 1.2
softdepend: [Vault]
commands:
    startevent:
        description: Start an event
        usage: /startevent <event>
        permission: meep.startevent
        permission-message: You don't have permission to do this.
    endevent:
        description: End an event
        usage: /endevent
        permission: meep.endevent
        permission-message: You don't have permission to do this.
    tradehour:
        description: Transports player to Trade Hour Market Location
        usage: /tradehour
        permission: meep.tradehour
        permission-message: You don't have permission to do this.
    settrade:
        description: Sets Location of Trade Hour Market
        usage: /settrade
        permission: meep.settrade
        permission-message: You don't have permission to do this.
    fight:
        description: Go help defend the west gates!
        usage: /fight
        permission: meep.fight
        permission-message: You don't have permission to do this.
    setwestgates:
        description: Set the location of the west gates for Mob attack
        usage: /setwestgates
        permission: meep.setgates
        permission-message: You don't have permission to do this.
permissions:
    meep.standard:
        description: Standard permissions for players
        default: true
        children:
            meep.tradehour: true
            meep.fight: true
    meep.admin:
        description: Admin permissions set
        default: op
        children:
            meep.settrade: true
            meep.startevent: true
            meep.endevent: true
            meep.avoidmob: true
            meep.setgates: true
    meep.tradehour:
        description: Allows to use tradehour command during Trade Hour
        default: true
    meep.fight:
        description: Allows player to teleport to the west gates for battle
        default: true
    meep.setgates:
        description: Allow player to set teleport location for the west gates
        default: op
    meep.settrade:
        description: Allows to set tradehour location
        default: op
    meep.startevent:
        description: Allows to start an event
        default: op
    meep.endevent:
        description: Allows to ends an event
        default: op
    meep.avoidmob:
        description: Makes mobs not target you during Mob Attack
        default: op